<?php

namespace DispoCar\ParcAutoBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * BoiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoiteRepository extends EntityRepository
{
}
