reservation_homepage:
    path:     /
    defaults: { _controller: ReservationBundle:Default:index }

gestion_reservation:
     path:     /gesReservation
     defaults: { _controller: ReservationBundle:Default:gesReservation }

