<?php

namespace DispoCar\AgenceBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * PointLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointLocationRepository extends EntityRepository
{
}
