<?php

namespace DispoCar\ReservationBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * NondispoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NondispoRepository extends EntityRepository
{
}
