utilisateur:
    resource: "@UtilisateurBundle/Controller/"
    type:     annotation
    prefix:   /

index:
    resource: "@IndexBundle/Resources/config/routing.yml"
    prefix:   /

abonnement:
    resource: "@AbonnementBundle/Resources/config/routing.yml"
    prefix:   /abonnement

reservation:
    resource: "@ReservationBundle/Resources/config/routing.yml"
    prefix:   /reservation

agence:
    resource: "@AgenceBundle/Resources/config/routing.yml"
    prefix:   /agence

parc_auto:
    resource: "@ParcAutoBundle/Resources/config/routing.yml"
    prefix:   /parcauto
