<?php

namespace parcAutoBundle\Repository;

/**
 * BoiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoiteRepository extends \Doctrine\ORM\EntityRepository
{
}
