<?php

namespace DispoCar\AbonnementBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * PrivilegeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrivilegeRepository extends EntityRepository
{
}
