<?php

namespace AbonnementBundle\Repository;

/**
 * ModeReglementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeReglementRepository extends \Doctrine\ORM\EntityRepository
{
}
