<?php

namespace AgenceBundle\Repository;

/**
 * PointLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointLocationRepository extends \Doctrine\ORM\EntityRepository
{
}
